FROM ubuntu:22.04

RUN apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install -qq \
  git \
  wget \
  python2 \
  python3 \
  python3-venv \
  tar \
  p7zip-full \
  cmake \
  software-properties-common \
  build-essential \
  curl zip unzip tar \  
  pkg-config \
  autoconf \
  cmake \
  ninja-build \
  flex \
  bison \
  libgsasl7 \
  libkrb5-3 \
  && apt-get clean -qq

RUN apt-get install -y libc-client-dev libkrb5-dev

RUN apt-get install -y libc-client-dev libgsasl7-dev

RUN apt-get install -y libc-client-dev uuid-dev

ADD ./entrypoint-build.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
