name: NES Dependencies builder

on:
  push:
    tags:
      - 'v*'

jobs:
  build-x64-linux:
    runs-on: ${{ matrix.target }}
    strategy:
      matrix:
        osversion: [ubuntu-18.04, ubuntu-20.04, ubuntu-21.10]
        arch: [ARM64]
        include:
        - arch: X64
          triplet: x64-linux
        - arch: ARM64
          triplet: arm64-linux
          target: [self-hosted, linux, ARM64, dep-builder]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set output vars to the actual tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build Docker
        id: builddocker
        working-directory: ${{ github.workspace }}/docker/
        run: docker build  -t nes_dep_build_${{ matrix.osversion }} -f Dockerfile-${{ matrix.osversion }} .
      - name: Install vcpkg
        id: bootstrapvcpkg
        run: |
          docker run -v ${{ github.workspace }}:/build_dir nes_dep_build_${{ matrix.osversion }} ./build_dir/vcpkg/bootstrap-vcpkg.sh -disableMetrics
        shell: bash
      - name: Install dependencies in manifest mode
        env:
          VCPKG_DEP_LIST: ${{ matrix.triplet }}
        id: installdeps
        run: |
          docker run -v ${{ github.workspace }}:/build_dir nes_dep_build_${{ matrix.osversion }} \
          ./build_dir/vcpkg/vcpkg install --triplet=${{ env.VCPKG_DEP_LIST }}-nes \
          --host-triplet=${{ env.VCPKG_DEP_LIST }}-nes --overlay-triplets=/build_dir/custom-triplets/ --x-manifest-root=/build_dir/ --overlay-ports=/build_dir/vcpkg-registry/ports
      - name: Compress artifacts
        env:
          VCPKG_DEP_LIST: ${{ matrix.triplet }}
        id: compressdeps
        run: |
          mkdir nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes && \
          mv ${{ github.workspace }}/vcpkg_installed nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes/installed && \
          mkdir -p nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes/scripts/buildsystems && \
          cp ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake ${{ github.workspace }}/nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes/scripts/buildsystems/ && \
          touch ${{ github.workspace }}/nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes/.vcpkg-root && \
          7z a nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-${{ matrix.osversion }}-nes.7z nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes -mx9 -aoa
      - name: Release
        env:
          VCPKG_DEP_LIST: ${{ matrix.triplet }}
        uses: softprops/action-gh-release@v1
        id: createrelease
        with:
          files: |
            nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-${{ matrix.osversion }}-nes.7z
      - name: Upload GitHub Actions artifact of vcpkg build logs
        env:
          VCPKG_DEP_LIST: ${{ matrix.triplet }}
        uses: actions/upload-artifact@v2
        if: failure()
        id: uploadlogs
        with:
          name: vcpkg-logs-${{ env.VCPKG_DEP_LIST }}
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
      - name: Clean build artifacts
        id: cleanbuildartifacts
        run: |
          rm -rf nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes.7z