name: NES Dependencies builder

on: [push]

jobs:
  build-x64-linux:
    env:
      VCPKG_DEP_LIST: x64-linux
      VCPKG_FEATURE_FLAGS: -binarycaching
    runs-on: [self-hosted, linux, X64, dep-builder]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install vcpkg
        id: installvcpkg
        run: |
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh -disableMetrics
        shell: bash
      - name: Install dependencies
        run: |
          ${{ github.workspace }}/build.sh ${{ env.VCPKG_DEP_LIST }}
      - name: Upload GitHub Actions artifact of vcpkg build logs
        uses: actions/upload-artifact@v2
        if: failure()
        id: uploadlogs
        with:
          name: vcpkg-logs-x64-linux
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
  build-arm64-linux:
    env:
      VCPKG_DEP_LIST: arm64-linux
      VCPKG_FORCE_SYSTEM_BINARIES: 1
      VCPKG_MAX_CONCURRENCY: 1
      VCPKG_FEATURE_FLAGS: -binarycaching
    runs-on: [self-hosted, linux, ARM64, dep-builder]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install vcpkg
        id: installvcpkg
        run: |
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh -useSystemBinaries -disableMetrics
        shell: bash
      - name: Install dependencies
        run: |
          ${{ github.workspace }}/build.sh ${{ env.VCPKG_DEP_LIST }}
      - name: Upload GitHub Actions artifact of vcpkg build logs
        uses: actions/upload-artifact@v2
        if: failure()
        id: uploadlogs
        with:
          name: vcpkg-logs-arm64-linux
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log