name: NES Dependencies builder

on:
  push:
    tags:
      - 'v*'

jobs:
  build-x64-linux:
    env:
      VCPKG_DEP_LIST: x64-linux
      VCPKG_FEATURE_FLAGS: -binarycaching
    runs-on: [self-hosted, linux, X64, dep-builder]
    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set output vars to the actual tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Install vcpkg
        id: bootstrapvcpkg
        run: |
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh -disableMetrics
        shell: bash
      - name: Install dependencies in manifest mode
        id: installdeps
        run: |
          ${{ github.workspace }}/vcpkg/vcpkg install --triplet=${{ env.VCPKG_DEP_LIST }}-nes --host-triplet=${{ env.VCPKG_DEP_LIST }}-nes --overlay-triplets=custom-triplets/
      - name: Compress artifacts
        id: compressdeps
        run: |
          mkdir nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes && \
          mv ${{ github.workspace }}/vcpkg_installed nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes/installed && \
          mkdir -p nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes/scripts/buildsystems && \
          cp ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake ${{ github.workspace }}/nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes/scripts/buildsystems/ && \
          touch ${{ github.workspace }}/nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes/installed/.vcpkg-root && \
          7z a nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes.7z nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes -mx9 -aoa
      - name: Release
        uses: softprops/action-gh-release@v1
        id: createrelease
        with:
          files: |
            nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes.7z
      - name: Upload GitHub Actions artifact of vcpkg build logs
        uses: actions/upload-artifact@v2
        if: failure()
        id: uploadlogs
        with:
          name: vcpkg-logs-${{ env.VCPKG_DEP_LIST }}
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
      - name: Clean build artifacts
        id: cleanbuildartifacts
        run: |
          nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes.7z
  build-arm64-linux:
    env:
      VCPKG_DEP_LIST: arm64-linux
      VCPKG_FORCE_SYSTEM_BINARIES: 1
      VCPKG_FEATURE_FLAGS: -binarycaching
    runs-on: [self-hosted, linux, ARM64, dep-builder]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set output vars to the actual tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Install vcpkg
        id: bootstrapvcpkg
        run: |
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh -disableMetrics
        shell: bash
      - name: Install dependencies in manifest mode
        id: installdeps
        run: |
          ${{ github.workspace }}/vcpkg/vcpkg install --triplet=${{ env.VCPKG_DEP_LIST }}-nes --host-triplet=${{ env.VCPKG_DEP_LIST }}-nes --overlay-triplets=custom-triplets/
      - name: Compress artifacts
        id: compressdeps
        run: |
          mkdir nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes && \
          mv ${{ github.workspace }}/vcpkg_installed nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes/installed && \
          mkdir -p nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes/scripts/buildsystems && \
          cp ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake ${{ github.workspace }}/nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes/scripts/buildsystems/ && \
          touch ${{ github.workspace }}/nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes/installed/.vcpkg-root && \
          7z a nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes.7z nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes -mx9 -aoa
      - name: Release
        uses: softprops/action-gh-release@v1
        id: createrelease
        with:
          files: |
            nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes.7z
      - name: Upload GitHub Actions artifact of vcpkg build logs
        uses: actions/upload-artifact@v2
        if: failure()
        id: uploadlogs
        with:
          name: vcpkg-logs-${{ env.VCPKG_DEP_LIST }}
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
      - name: Clean build artifacts
        id: cleanbuildartifacts
        run: |
          nes-dependencies-${{ steps.vars.outputs.tag }}-${{ env.VCPKG_DEP_LIST }}-nes.7z