name: NES Dependencies builder

on: [push]

jobs:
  build-x64-linux:
    env:
      VCPKG_DEP_LIST: x64-linux
      VCPKG_FEATURE_FLAGS: -binarycaching
    runs-on: [self-hosted, linux, X64, dep-builder]
    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Create build directory
        id: builddir
        run: |
          rm -rf ${{ github.workspace }}/build && mkdir -p ${{ github.workspace }}/build
      - name: Install vcpkg
        id: bootstrapvcpkg
        run: |
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh -disableMetrics
        shell: bash
      - name: Install dependencies in manifest mode
        id: installdeps
        run: |
          cmake -B build -S ${{ github.workspace }} -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake && cmake --build ${{ github.workspace }}/build
      - name: Build dependencies
        id: builddeps
        run: |
          cmake --build ${{ github.workspace }}/build
      - name: Compress artifacts
        id: compressdeps
        run: |
          mkdir nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes && \
          mv ${{ github.workspace }}/build/vcpkg_installed nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes/installed && \
          mkdir -p nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes/scripts/buildsystems && \
          cp ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake ${{ github.workspace }}/nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes/scripts/buildsystems/ && \
          touch ${{ github.workspace }}/nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes/installed/.vcpkg-root && \
          7z a nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes.7z nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes
      - name: Upload GitHub Actions artifact of vcpkg build logs
        uses: actions/upload-artifact@v2
        if: failure()
        id: uploadlogs
        with:
          name: vcpkg-logs-x64-linux
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
  build-arm64-linux:
    env:
      VCPKG_DEP_LIST: arm64-linux
      VCPKG_FORCE_SYSTEM_BINARIES: 1
      VCPKG_FEATURE_FLAGS: -binarycaching
    runs-on: [self-hosted, linux, ARM64, dep-builder]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Create build directory
        id: builddir
        run: |
          rm -rf ${{ github.workspace }}/build && mkdir -p ${{ github.workspace }}/build
      - name: Install vcpkg
        id: bootstrapvcpkg
        run: |
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh -disableMetrics
        shell: bash
      - name: Install dependencies in manifest mode
        id: installdeps
        run: |
          cmake -B build -S ${{ github.workspace }} -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake && cmake --build ${{ github.workspace }}/build
      - name: Build dependencies
        id: builddeps
        run: |
          cmake --build ${{ github.workspace }}/build
      - name: Compress artifacts
        id: compressdeps
        run: |
          mkdir nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes && \
          mv ${{ github.workspace }}/build/vcpkg_installed nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes/installed && \
          mkdir -p nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes/scripts/buildsystems && \
          cp ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake ${{ github.workspace }}/nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes/scripts/buildsystems/ && \
          touch ${{ github.workspace }}/nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes/installed/.vcpkg-root && \
          7z a nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes.7z nes-dependencies-${{ env.VCPKG_DEP_LIST }}-nes
      - name: Upload GitHub Actions artifact of vcpkg build logs
        uses: actions/upload-artifact@v2
        if: failure()
        id: uploadlogs
        with:
          name: vcpkg-logs-arm64-linux
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log